blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import CategoryListView, contacts, ProductDetailView
from catalog.views import ProductsListView, CategoryProductsListView, ProductCreateView, ProductUpdateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='index'),
    path('products/', ProductsListView.as_view(), name='products'),
    path('contacts/', contacts, name='contacts'),
    path('<int:pk>/catalog/', CategoryProductsListView.as_view(), name='category_products'),
    path('<int:pk>/product/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('<int:pk>/catalog/create', ProductCreateView.as_view(), name='product_create'),
    path('<int:pk>/catalog/edit', ProductUpdateView.as_view(), name='edit'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, CodeView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('code/', CodeView.as_view(), name='verify_code'),
]

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='наименование')
    product_content = models.TextField(verbose_name='описание')
    product_image = models.ImageField(upload_to='catalog/', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    price_for_one = models.IntegerField(verbose_name='цена')
    date_created = models.DateTimeField(auto_now_add=True)
    date_last_change = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.product_name} {self.product_content}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

        permissions = [
            ('set_is_published', 'Может публиковать товары'),
            ('set_product_content', 'Может менять описание'),
            ('set_category', 'Может менять категорию'),
        ]


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='наименование')
    category_content = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Version(models.Model):

    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='имя версии')
    current_version_indicator = models.BooleanField(default=True, verbose_name='признак текущей версии')

    def __str__(self):
        return f'{self.product, self.version_name}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def init(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'product_content', 'product_image', 'category', 'price_for_one')

    def clean_product_name(self):
        cleaned_data = self.cleaned_data['product_name']
        wrong_product_name = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                              'радар']
        for word in wrong_product_name:
            if word in cleaned_data:
                raise forms.ValidationError('Недопустимое название продукта')
        return cleaned_data

    def clean_product_content(self):
        cleaned_data = self.cleaned_data['product_content']
        wrong_content_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                               'радар']
        for word in wrong_content_words:
            if word in cleaned_data:
                raise forms.ValidationError('Недопустимое название в описании')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Category, Product, Version
from catalog.services import get_categories_cache


@login_required
def contacts(requests):
    return render(requests, 'catalog/contacts.html')


class ProductsListView(ListView):
    model = Category
    extra_context = {
        'title': 'Наш ассортимент'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Category.objects.all()[:3]
        return context_data


class CategoryListView(ListView):
    model = Category

    get_categories_cache()

    extra_context = {
        'title': 'Все категории техники'
    }


class CategoryProductsListView(ListView):
    model = Product

    def get_queryset(self):
        return super().get_queryset().filter(
            category_id=self.kwargs.get('pk'),
            user=self.request.user
        )

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'Все наши {category_item.category_name}'

        return context_data


class ProductDetailView(DetailView):
    model = Product
    template_name = 'catalog/product.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        product = Product.objects.get(id=self.kwargs.get('pk'))
        context_data['product_name'] = product.product_name
        context_data['product_content'] = product.product_content
        context_data['title'] = 'Выбранный товар'
        context_data['product_image'] = product.product_image
        context_data['price_for_one'] = f'Цена: {product.price_for_one} руб.'

        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if self.object.user != self.request.user:
            product_fields = [fields_key for fields_key in form.fields.key()]
            for field in product_fields:
                if not self.request.user.has_perm(f'catalog.set_{field}'):
                    del form.fields[field]

        return form

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('catalog:product', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О сайте</h4>
                    <p class="text-muted">Официальный сайт сети магазинов электроники. </p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'catalog:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'catalog:products' %}" class="text-white">Товары</a></li>
                        <li><a href="{% url 'blog:list' %}" class="text-white">Блог</a></li>
                        <li><a href="{% url 'catalog:contacts' %}" class="text-white">Контакты</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                            <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                            <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>KudryaElectronics</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content%}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="col-6 col-md">
        <h5>Дополнительно</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Мы пишем</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
        <h5>О нас</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="/contacts/">Контакты</a></li>
        </ul>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/vendor/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="row">
    {% for object in object_list%}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.category_name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:category_products' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">К товарам</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/category_products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content%}
<div class="row">
    {% for object in object_list%}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.product_image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.product_name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/categoryproducts_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content%}
<div class="row">
    {% for object in object_list%}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.product_image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.product_name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Тюмень</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="row">
    {% for object in object_list%}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.category_name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:category_products' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">К товару</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content%}
<div class="row">
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ product_image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ product_name }}</p>
                <p class="card-text">Описание:</p>
                <p class="card-text">{{ product_content }}</p>
                <p class="card-text">{{ price_for_one }}</p>
                <span class="text-muted">{{ user|default:'-' }}</span>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content%}
    <form method="post" class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        {% if object %}
                            Редактирование продукта
                        {% else %}
                            Добавление продукта
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Добавить
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        Версия
                    </div>
                    <div class="card-body">
                        {{ formset.management_form}}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                            <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
    </form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="row">
    <div class="col-12 mb-5">
        <a class="btn btn-primary" href="{% url 'catalog:product_create' category_pk %}">Добавить продукт</a>
    </div>
    {% for object in object_list%}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.product_name }}</p>
                <span class="text-muted"></span>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:product' object.id %}" type="button" class="btn btn-sm btn-outline-secondary">К товару</a>
                        <a href="{% url 'catalog:edit' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}

{% block content%}
<div class="row">
    {% for object in object_list%}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">{{ object.product_name }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:product' object.id %}" type="button" class="btn btn-sm btn-outline-secondary">К товару</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}